name: HACS validation

"on":
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    name: Validate with HACS
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
